name: notary
version: 0.1.1
author: Cristian Almstrand <cristian.almstrand@gmail.com>
homepage: https://github.com/almstrand/lib_notary
description: Server-side library to sign Google Cloud Storage HTTP requests and authorize file access (upload, download, etc.) via your website.
environment:
  sdk: '>=1.7.0-dev.2.0 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  googleapis_auth: ">=0.1.1 <0.2.0"
